/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.microservice;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;
import java.util.Optional;
@org.apache.avro.specific.AvroGenerated
public class Stock extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4886992214210982545L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Stock\",\"namespace\":\"com.microservice\",\"fields\":[{\"name\":\"symbol\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"date\",\"type\":\"long\"},{\"name\":\"open\",\"type\":\"double\"},{\"name\":\"high\",\"type\":\"double\"},{\"name\":\"low\",\"type\":\"double\"},{\"name\":\"close\",\"type\":\"double\"},{\"name\":\"volume\",\"type\":\"double\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<com.microservice.Stock> ENCODER =
      new BinaryMessageEncoder<com.microservice.Stock>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<com.microservice.Stock> DECODER =
      new BinaryMessageDecoder<com.microservice.Stock>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<com.microservice.Stock> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<com.microservice.Stock> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<com.microservice.Stock> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<com.microservice.Stock>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Stock to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Stock from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Stock instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static com.microservice.Stock fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String symbol;
  private java.lang.String name;
  private long date;
  private double open;
  private double high;
  private double low;
  private double close;
  private double volume;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Stock() {}

  /**
   * All-args constructor.
   * @param symbol The new value for symbol
   * @param name The new value for name
   * @param date The new value for date
   * @param open The new value for open
   * @param high The new value for high
   * @param low The new value for low
   * @param close The new value for close
   * @param volume The new value for volume
   */
  public Stock(java.lang.String symbol, java.lang.String name, java.lang.Long date, java.lang.Double open, java.lang.Double high, java.lang.Double low, java.lang.Double close, java.lang.Double volume) {
    this.symbol = symbol;
    this.name = name;
    this.date = date;
    this.open = open;
    this.high = high;
    this.low = low;
    this.close = close;
    this.volume = volume;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return symbol;
    case 1: return name;
    case 2: return date;
    case 3: return open;
    case 4: return high;
    case 5: return low;
    case 6: return close;
    case 7: return volume;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: symbol = value$ != null ? value$.toString() : null; break;
    case 1: name = value$ != null ? value$.toString() : null; break;
    case 2: date = (java.lang.Long)value$; break;
    case 3: open = (java.lang.Double)value$; break;
    case 4: high = (java.lang.Double)value$; break;
    case 5: low = (java.lang.Double)value$; break;
    case 6: close = (java.lang.Double)value$; break;
    case 7: volume = (java.lang.Double)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'symbol' field.
   * @return The value of the 'symbol' field.
   */
  public java.lang.String getSymbol() {
    return symbol;
  }

  /**
   * Gets the value of the 'symbol' field as an Optional&lt;java.lang.String&gt;.
   * @return The value wrapped in an Optional&lt;java.lang.String&gt;.
   */
  public Optional<java.lang.String> getOptionalSymbol() {
    return Optional.<java.lang.String>ofNullable(symbol);
  }

  /**
   * Sets the value of the 'symbol' field.
   * @param value the value to set.
   */
  public void setSymbol(java.lang.String value) {
    this.symbol = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * Gets the value of the 'name' field as an Optional&lt;java.lang.String&gt;.
   * @return The value wrapped in an Optional&lt;java.lang.String&gt;.
   */
  public Optional<java.lang.String> getOptionalName() {
    return Optional.<java.lang.String>ofNullable(name);
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.String value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'date' field.
   * @return The value of the 'date' field.
   */
  public long getDate() {
    return date;
  }

  /**
   * Gets the value of the 'date' field as an Optional&lt;java.lang.Long&gt;.
   * @return The value wrapped in an Optional&lt;java.lang.Long&gt;.
   */
  public Optional<java.lang.Long> getOptionalDate() {
    return Optional.<java.lang.Long>ofNullable(date);
  }

  /**
   * Sets the value of the 'date' field.
   * @param value the value to set.
   */
  public void setDate(long value) {
    this.date = value;
  }

  /**
   * Gets the value of the 'open' field.
   * @return The value of the 'open' field.
   */
  public double getOpen() {
    return open;
  }

  /**
   * Gets the value of the 'open' field as an Optional&lt;java.lang.Double&gt;.
   * @return The value wrapped in an Optional&lt;java.lang.Double&gt;.
   */
  public Optional<java.lang.Double> getOptionalOpen() {
    return Optional.<java.lang.Double>ofNullable(open);
  }

  /**
   * Sets the value of the 'open' field.
   * @param value the value to set.
   */
  public void setOpen(double value) {
    this.open = value;
  }

  /**
   * Gets the value of the 'high' field.
   * @return The value of the 'high' field.
   */
  public double getHigh() {
    return high;
  }

  /**
   * Gets the value of the 'high' field as an Optional&lt;java.lang.Double&gt;.
   * @return The value wrapped in an Optional&lt;java.lang.Double&gt;.
   */
  public Optional<java.lang.Double> getOptionalHigh() {
    return Optional.<java.lang.Double>ofNullable(high);
  }

  /**
   * Sets the value of the 'high' field.
   * @param value the value to set.
   */
  public void setHigh(double value) {
    this.high = value;
  }

  /**
   * Gets the value of the 'low' field.
   * @return The value of the 'low' field.
   */
  public double getLow() {
    return low;
  }

  /**
   * Gets the value of the 'low' field as an Optional&lt;java.lang.Double&gt;.
   * @return The value wrapped in an Optional&lt;java.lang.Double&gt;.
   */
  public Optional<java.lang.Double> getOptionalLow() {
    return Optional.<java.lang.Double>ofNullable(low);
  }

  /**
   * Sets the value of the 'low' field.
   * @param value the value to set.
   */
  public void setLow(double value) {
    this.low = value;
  }

  /**
   * Gets the value of the 'close' field.
   * @return The value of the 'close' field.
   */
  public double getClose() {
    return close;
  }

  /**
   * Gets the value of the 'close' field as an Optional&lt;java.lang.Double&gt;.
   * @return The value wrapped in an Optional&lt;java.lang.Double&gt;.
   */
  public Optional<java.lang.Double> getOptionalClose() {
    return Optional.<java.lang.Double>ofNullable(close);
  }

  /**
   * Sets the value of the 'close' field.
   * @param value the value to set.
   */
  public void setClose(double value) {
    this.close = value;
  }

  /**
   * Gets the value of the 'volume' field.
   * @return The value of the 'volume' field.
   */
  public double getVolume() {
    return volume;
  }

  /**
   * Gets the value of the 'volume' field as an Optional&lt;java.lang.Double&gt;.
   * @return The value wrapped in an Optional&lt;java.lang.Double&gt;.
   */
  public Optional<java.lang.Double> getOptionalVolume() {
    return Optional.<java.lang.Double>ofNullable(volume);
  }

  /**
   * Sets the value of the 'volume' field.
   * @param value the value to set.
   */
  public void setVolume(double value) {
    this.volume = value;
  }

  /**
   * Creates a new Stock RecordBuilder.
   * @return A new Stock RecordBuilder
   */
  public static com.microservice.Stock.Builder newBuilder() {
    return new com.microservice.Stock.Builder();
  }

  /**
   * Creates a new Stock RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Stock RecordBuilder
   */
  public static com.microservice.Stock.Builder newBuilder(com.microservice.Stock.Builder other) {
    if (other == null) {
      return new com.microservice.Stock.Builder();
    } else {
      return new com.microservice.Stock.Builder(other);
    }
  }

  /**
   * Creates a new Stock RecordBuilder by copying an existing Stock instance.
   * @param other The existing instance to copy.
   * @return A new Stock RecordBuilder
   */
  public static com.microservice.Stock.Builder newBuilder(com.microservice.Stock other) {
    if (other == null) {
      return new com.microservice.Stock.Builder();
    } else {
      return new com.microservice.Stock.Builder(other);
    }
  }

  /**
   * RecordBuilder for Stock instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<com.microservice.Stock>
    implements org.apache.avro.data.RecordBuilder<com.microservice.Stock> {

    private java.lang.String symbol;
    private java.lang.String name;
    private long date;
    private double open;
    private double high;
    private double low;
    private double close;
    private double volume;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.microservice.Stock.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.symbol)) {
        this.symbol = data().deepCopy(fields()[0].schema(), other.symbol);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.date)) {
        this.date = data().deepCopy(fields()[2].schema(), other.date);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.open)) {
        this.open = data().deepCopy(fields()[3].schema(), other.open);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.high)) {
        this.high = data().deepCopy(fields()[4].schema(), other.high);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.low)) {
        this.low = data().deepCopy(fields()[5].schema(), other.low);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.close)) {
        this.close = data().deepCopy(fields()[6].schema(), other.close);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.volume)) {
        this.volume = data().deepCopy(fields()[7].schema(), other.volume);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
    }

    /**
     * Creates a Builder by copying an existing Stock instance
     * @param other The existing instance to copy.
     */
    private Builder(com.microservice.Stock other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.symbol)) {
        this.symbol = data().deepCopy(fields()[0].schema(), other.symbol);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.date)) {
        this.date = data().deepCopy(fields()[2].schema(), other.date);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.open)) {
        this.open = data().deepCopy(fields()[3].schema(), other.open);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.high)) {
        this.high = data().deepCopy(fields()[4].schema(), other.high);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.low)) {
        this.low = data().deepCopy(fields()[5].schema(), other.low);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.close)) {
        this.close = data().deepCopy(fields()[6].schema(), other.close);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.volume)) {
        this.volume = data().deepCopy(fields()[7].schema(), other.volume);
        fieldSetFlags()[7] = true;
      }
    }

    /**
      * Gets the value of the 'symbol' field.
      * @return The value.
      */
    public java.lang.String getSymbol() {
      return symbol;
    }

    /**
      * Gets the value of the 'symbol' field as an Optional&lt;java.lang.String&gt;.
      * @return The value wrapped in an Optional&lt;java.lang.String&gt;.
      */
    public Optional<java.lang.String> getOptionalSymbol() {
      return Optional.<java.lang.String>ofNullable(symbol);
    }

    /**
      * Sets the value of the 'symbol' field.
      * @param value The value of 'symbol'.
      * @return This builder.
      */
    public com.microservice.Stock.Builder setSymbol(java.lang.String value) {
      validate(fields()[0], value);
      this.symbol = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'symbol' field has been set.
      * @return True if the 'symbol' field has been set, false otherwise.
      */
    public boolean hasSymbol() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'symbol' field.
      * @return This builder.
      */
    public com.microservice.Stock.Builder clearSymbol() {
      symbol = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.String getName() {
      return name;
    }

    /**
      * Gets the value of the 'name' field as an Optional&lt;java.lang.String&gt;.
      * @return The value wrapped in an Optional&lt;java.lang.String&gt;.
      */
    public Optional<java.lang.String> getOptionalName() {
      return Optional.<java.lang.String>ofNullable(name);
    }

    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.microservice.Stock.Builder setName(java.lang.String value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.microservice.Stock.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'date' field.
      * @return The value.
      */
    public long getDate() {
      return date;
    }

    /**
      * Gets the value of the 'date' field as an Optional&lt;java.lang.Long&gt;.
      * @return The value wrapped in an Optional&lt;java.lang.Long&gt;.
      */
    public Optional<java.lang.Long> getOptionalDate() {
      return Optional.<java.lang.Long>ofNullable(date);
    }

    /**
      * Sets the value of the 'date' field.
      * @param value The value of 'date'.
      * @return This builder.
      */
    public com.microservice.Stock.Builder setDate(long value) {
      validate(fields()[2], value);
      this.date = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'date' field has been set.
      * @return True if the 'date' field has been set, false otherwise.
      */
    public boolean hasDate() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'date' field.
      * @return This builder.
      */
    public com.microservice.Stock.Builder clearDate() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'open' field.
      * @return The value.
      */
    public double getOpen() {
      return open;
    }

    /**
      * Gets the value of the 'open' field as an Optional&lt;java.lang.Double&gt;.
      * @return The value wrapped in an Optional&lt;java.lang.Double&gt;.
      */
    public Optional<java.lang.Double> getOptionalOpen() {
      return Optional.<java.lang.Double>ofNullable(open);
    }

    /**
      * Sets the value of the 'open' field.
      * @param value The value of 'open'.
      * @return This builder.
      */
    public com.microservice.Stock.Builder setOpen(double value) {
      validate(fields()[3], value);
      this.open = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'open' field has been set.
      * @return True if the 'open' field has been set, false otherwise.
      */
    public boolean hasOpen() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'open' field.
      * @return This builder.
      */
    public com.microservice.Stock.Builder clearOpen() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'high' field.
      * @return The value.
      */
    public double getHigh() {
      return high;
    }

    /**
      * Gets the value of the 'high' field as an Optional&lt;java.lang.Double&gt;.
      * @return The value wrapped in an Optional&lt;java.lang.Double&gt;.
      */
    public Optional<java.lang.Double> getOptionalHigh() {
      return Optional.<java.lang.Double>ofNullable(high);
    }

    /**
      * Sets the value of the 'high' field.
      * @param value The value of 'high'.
      * @return This builder.
      */
    public com.microservice.Stock.Builder setHigh(double value) {
      validate(fields()[4], value);
      this.high = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'high' field has been set.
      * @return True if the 'high' field has been set, false otherwise.
      */
    public boolean hasHigh() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'high' field.
      * @return This builder.
      */
    public com.microservice.Stock.Builder clearHigh() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'low' field.
      * @return The value.
      */
    public double getLow() {
      return low;
    }

    /**
      * Gets the value of the 'low' field as an Optional&lt;java.lang.Double&gt;.
      * @return The value wrapped in an Optional&lt;java.lang.Double&gt;.
      */
    public Optional<java.lang.Double> getOptionalLow() {
      return Optional.<java.lang.Double>ofNullable(low);
    }

    /**
      * Sets the value of the 'low' field.
      * @param value The value of 'low'.
      * @return This builder.
      */
    public com.microservice.Stock.Builder setLow(double value) {
      validate(fields()[5], value);
      this.low = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'low' field has been set.
      * @return True if the 'low' field has been set, false otherwise.
      */
    public boolean hasLow() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'low' field.
      * @return This builder.
      */
    public com.microservice.Stock.Builder clearLow() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'close' field.
      * @return The value.
      */
    public double getClose() {
      return close;
    }

    /**
      * Gets the value of the 'close' field as an Optional&lt;java.lang.Double&gt;.
      * @return The value wrapped in an Optional&lt;java.lang.Double&gt;.
      */
    public Optional<java.lang.Double> getOptionalClose() {
      return Optional.<java.lang.Double>ofNullable(close);
    }

    /**
      * Sets the value of the 'close' field.
      * @param value The value of 'close'.
      * @return This builder.
      */
    public com.microservice.Stock.Builder setClose(double value) {
      validate(fields()[6], value);
      this.close = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'close' field has been set.
      * @return True if the 'close' field has been set, false otherwise.
      */
    public boolean hasClose() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'close' field.
      * @return This builder.
      */
    public com.microservice.Stock.Builder clearClose() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'volume' field.
      * @return The value.
      */
    public double getVolume() {
      return volume;
    }

    /**
      * Gets the value of the 'volume' field as an Optional&lt;java.lang.Double&gt;.
      * @return The value wrapped in an Optional&lt;java.lang.Double&gt;.
      */
    public Optional<java.lang.Double> getOptionalVolume() {
      return Optional.<java.lang.Double>ofNullable(volume);
    }

    /**
      * Sets the value of the 'volume' field.
      * @param value The value of 'volume'.
      * @return This builder.
      */
    public com.microservice.Stock.Builder setVolume(double value) {
      validate(fields()[7], value);
      this.volume = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'volume' field has been set.
      * @return True if the 'volume' field has been set, false otherwise.
      */
    public boolean hasVolume() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'volume' field.
      * @return This builder.
      */
    public com.microservice.Stock.Builder clearVolume() {
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public com.microservice.Stock build() {
      try {
        com.microservice.Stock record = new com.microservice.Stock();
        record.symbol = fieldSetFlags()[0] ? this.symbol : (java.lang.String) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.String) defaultValue(fields()[1]);
        record.date = fieldSetFlags()[2] ? this.date : (java.lang.Long) defaultValue(fields()[2]);
        record.open = fieldSetFlags()[3] ? this.open : (java.lang.Double) defaultValue(fields()[3]);
        record.high = fieldSetFlags()[4] ? this.high : (java.lang.Double) defaultValue(fields()[4]);
        record.low = fieldSetFlags()[5] ? this.low : (java.lang.Double) defaultValue(fields()[5]);
        record.close = fieldSetFlags()[6] ? this.close : (java.lang.Double) defaultValue(fields()[6]);
        record.volume = fieldSetFlags()[7] ? this.volume : (java.lang.Double) defaultValue(fields()[7]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<com.microservice.Stock>
    WRITER$ = (org.apache.avro.io.DatumWriter<com.microservice.Stock>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<com.microservice.Stock>
    READER$ = (org.apache.avro.io.DatumReader<com.microservice.Stock>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.symbol);

    out.writeString(this.name);

    out.writeLong(this.date);

    out.writeDouble(this.open);

    out.writeDouble(this.high);

    out.writeDouble(this.low);

    out.writeDouble(this.close);

    out.writeDouble(this.volume);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.symbol = in.readString();

      this.name = in.readString();

      this.date = in.readLong();

      this.open = in.readDouble();

      this.high = in.readDouble();

      this.low = in.readDouble();

      this.close = in.readDouble();

      this.volume = in.readDouble();

    } else {
      for (int i = 0; i < 8; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.symbol = in.readString();
          break;

        case 1:
          this.name = in.readString();
          break;

        case 2:
          this.date = in.readLong();
          break;

        case 3:
          this.open = in.readDouble();
          break;

        case 4:
          this.high = in.readDouble();
          break;

        case 5:
          this.low = in.readDouble();
          break;

        case 6:
          this.close = in.readDouble();
          break;

        case 7:
          this.volume = in.readDouble();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










